# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About us
    url: /
    weight: 10
  - name: Team
    url: /#team
    weight: 11
  - name: Projects
    url: /#projects
    weight: 12
  - name: Publications
    url: /#papers
    weight: 13
  - name: Join
    url: /#contact
    weight: 20
 # - name: Projects
 #   url: projects/
 #   weight: 30
  # - name: Courses
   # url: courses/
   # weight: 40
